[versions]
kotlin = "2.1.21"
kover = "0.8.3"
detekt = "1.23.8"
dokka = "2.0.0"
ksp = "2.1.21-2.0.2"
maven = "0.30.0"
ktor = "3.1.3"
mockk = "1.13.12"
jsoup = "1.16.2"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.8.1"
kotlinx-io = "0.7.0"
zstd = "1.5.7-4"
opentelemetry = "1.56.0"

[plugins]
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
maven = { id = "com.vanniktech.maven.publish", version.ref = "maven" }

[libraries]
ktor-serializationKotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-clientWebsockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-clientContentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-clientApache = { module = "io.ktor:ktor-client-apache", version.ref = "ktor" }
ktor-clientCio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-clientJs = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-clientDarwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-clientCurl = { module = "io.ktor:ktor-client-curl", version.ref = "ktor" }
ktor-clientWinhttp = { module = "io.ktor:ktor-client-winhttp", version.ref = "ktor" }
tests-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
tests-jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
tests-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
zstd = { module = "com.github.luben:zstd-jni", version.ref = "zstd" }
opentelemetry-extension-kotlin = { module = "io.opentelemetry:opentelemetry-extension-kotlin", version.ref = "opentelemetry" }
opentelemetry-sdk-testing = { module = "io.opentelemetry:opentelemetry-sdk-testing", version.ref = "opentelemetry" }
